asset = ""
current_timestamp = ""
deposit_timestamp = ""
liquidity = ""
nullifier = ""
nullifier_hash = ""
proof_path_indices = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
proof_siblings = ["", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", ""]
root = ""
secret = ""
